volumes:
  caddy_data:
  caddy_config:
  frontend_build:

services:
  caddy:
      image: docker.io/library/caddy:2-alpine
      ports:
        - "8080:80"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:Z
        - caddy_data:/data
        - frontend_build:/var/www/html:ro
        - caddy_config:/config
      depends_on:
        - backend
        - frontend
  backend:
    build:
      context: ./backend/
      target: development
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    develop:
      watch:
        - action: restart
          path: ./config.toml
        - action: rebuild
          path: ./backend/Dockerfile
        - action: rebuild
          path: ./backend/pyproject.toml
          target: /backend/pyproject.toml
        - action: sync
          path: ./backend
          target: /backend
  frontend:
    image: docker.io/oven/bun:slim
    working_dir: /app
    volumes:
      - ./frontend:/app:Z
      - frontend_build:/app/dist:Z
    command: sh -c "bun run dev --host 0.0.0.0"
